# Generated for ScoutBox v0.7.3 to adopt the pre-migration portal schema.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovery_mode', models.CharField(max_length=32, choices=[('source_guided', 'Source-Guided Discovery'), ('cloud_web', 'Cloud Web Discovery')], default='source_guided')),
                ('background_paused', models.BooleanField(default=False)),
                ('scraper_interval_minutes', models.PositiveIntegerField(default=120)),
                ('keywords_per_run', models.PositiveIntegerField(default=12)),
                ('queries_per_provider', models.PositiveIntegerField(default=8)),
                ('provider_daily_request_budget', models.PositiveIntegerField(default=100)),
                ('max_results_per_query', models.PositiveIntegerField(default=10)),
                ('duplicate_window_days', models.PositiveIntegerField(default=90)),
                ('draft_suppression_days', models.PositiveIntegerField(default=90)),
                ('company_reapply_window_days', models.PositiveIntegerField(default=90, help_text='Different roles at a recently applied company remain visible but are ranked down within this window.')),
                ('same_company_fit_penalty', models.PositiveSmallIntegerField(default=20, help_text='Score penalty for a different role at a company applied to within the company cooldown window.')),
                ('same_company_unknown_date_penalty', models.PositiveSmallIntegerField(default=8, help_text='Smaller caution penalty when a prior application at the same company has no reliable application date.')),
                ('search_jitter_percent', models.PositiveIntegerField(default=15)),
                ('last_discovery_run', models.DateTimeField(null=True, blank=True)),
                ('last_scheduler_tick', models.DateTimeField(null=True, blank=True)),
                ('last_mail_sync', models.DateTimeField(null=True, blank=True)),
                ('digest_enabled', models.BooleanField(default=True)),
                ('digest_hour', models.PositiveSmallIntegerField(default=8)),
                ('digest_minute', models.PositiveSmallIntegerField(default=30)),
                ('last_digest_sent', models.DateField(null=True, blank=True)),
                ('feature_page_fetch', models.BooleanField(default=True)),
                ('feature_age_estimation', models.BooleanField(default=True)),
                ('feature_wayback', models.BooleanField(default=True)),
                ('feature_company_enrichment', models.BooleanField(default=True)),
                ('feature_contact_discovery', models.BooleanField(default=True)),
                ('feature_cross_source', models.BooleanField(default=True)),
                ('feature_ai_rerank', models.BooleanField(default=True)),
                ('feature_authenticated_social_fetch', models.BooleanField(default=True)),
                ('feature_facebook_index_search', models.BooleanField(default=True)),
                ('feature_blog_click_sync', models.BooleanField(default=True)),
                ('feature_page_summarization', models.BooleanField(default=True)),
                ('feature_deep_jd_analysis', models.BooleanField(default=True)),
                ('feature_document_conversion', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200, blank=True)),
                ('operating_location', models.CharField(max_length=120, default='Singapore')),
                ('application_email', models.EmailField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('high_priority_text', models.TextField(blank=True, default='Embedded systems, reverse engineering, retro computing, QEMU/virtualization, legacy systems and rare specialist roles.')),
                ('medium_priority_text', models.TextField(blank=True, default='Technical writing, remote teaching/training, consulting and adjacent low-level tooling with concrete fit and a short process.')),
                ('low_priority_text', models.TextField(blank=True, default='Interesting adjacent OSS/support or unusual software work. Avoid low-rate marketplaces and clearly unsuitable engagement models.')),
                ('scope_json', models.JSONField(default=dict, blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20, choices=[('cv', 'CV'), ('cover', 'Cover letter')])),
                ('label', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('original_name', models.CharField(max_length=255, blank=True)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('source_type', models.CharField(max_length=40, default='web')),
                ('base_url', models.URLField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=50)),
                ('provider_weight', models.PositiveSmallIntegerField(default=100)),
                ('daily_budget_override', models.PositiveIntegerField(null=True, blank=True)),
                ('low_value_marketplace', models.BooleanField(default=False)),
                ('requires_credentials', models.BooleanField(default=False)),
                ('adapter_status', models.CharField(max_length=40, default='preset')),
                ('notes', models.TextField(blank=True)),
                ('config_json', models.JSONField(default=dict, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchProviderStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='portal.searchsource')),
                ('day', models.DateField(default=timezone.localdate)),
                ('requests', models.PositiveIntegerField(default=0)),
                ('results', models.PositiveIntegerField(default=0)),
                ('unique_results', models.PositiveIntegerField(default=0)),
                ('duplicates', models.PositiveIntegerField(default=0)),
                ('applied_matches', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('quota_units', models.DecimalField(max_digits=12, decimal_places=2, default=0)),
                ('avg_latency_ms', models.PositiveIntegerField(default=0)),
                ('bytes_downloaded', models.PositiveBigIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={'unique_together': {('source', 'day')}},
        ),
        migrations.CreateModel(
            name='FacebookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_search_index', models.BooleanField(default=True)),
                ('use_graph_api', models.BooleanField(default=True)),
                ('use_authenticated_cookie', models.BooleanField(default=True)),
                ('graph_access_token_enc', models.TextField(blank=True)),
                ('graph_page_ids', models.TextField(blank=True, help_text='Comma/newline separated public Page IDs to watch.')),
                ('cookie_header_enc', models.TextField(blank=True, help_text='Cookie header copied from a browser session you logged into yourself.')),
                ('last_test_ok', models.BooleanField(default=False)),
                ('last_test_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('template', models.CharField(max_length=120, blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=160, default='Singapore')),
                ('role_families', models.TextField(blank=True)),
                ('technologies', models.TextField(blank=True)),
                ('engagement_types', models.TextField(blank=True)),
                ('company_sizes', models.TextField(blank=True)),
                ('languages', models.TextField(blank=True)),
                ('negative_constraints', models.TextField(blank=True)),
                ('extra_text', models.TextField(blank=True)),
                ('recency_days', models.PositiveIntegerField(default=30)),
                ('source_names', models.JSONField(default=list, blank=True)),
                ('last_run', models.DateTimeField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40, default='search_test')),
                ('started_at', models.DateTimeField(default=timezone.now)),
                ('finished_at', models.DateTimeField(null=True, blank=True)),
                ('ok', models.BooleanField(default=False)),
                ('criteria', models.JSONField(default=dict, blank=True)),
                ('result', models.JSONField(default=dict, blank=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={'ordering': ['-started_at']},
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=220, blank=True)),
                ('country', models.CharField(max_length=120, blank=True)),
                ('remote_text', models.CharField(max_length=220, blank=True)),
                ('url', models.URLField(max_length=1000)),
                ('canonical_url', models.URLField(max_length=1000, blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, to='portal.searchsource')),
                ('campaigns', models.ManyToManyField(blank=True, related_name='opportunities', to='portal.campaign')),
                ('channel', models.CharField(max_length=30, choices=[('email', 'Direct email'), ('ats', 'ATS'), ('website', 'Website form'), ('public', 'Public post'), ('community', 'Community'), ('unknown', 'Unknown')], default='unknown')),
                ('contact_email', models.EmailField(blank=True)),
                ('contact_name', models.CharField(max_length=200, blank=True)),
                ('description', models.TextField(blank=True)),
                ('raw_search_snippet', models.TextField(blank=True)),
                ('extracted_facts', models.JSONField(default=dict, blank=True)),
                ('company_intel', models.JSONField(default=dict, blank=True)),
                ('status', models.CharField(max_length=30, choices=[('new', 'New'), ('apply', 'Apply Now'), ('review', 'Review'), ('info', 'Information Only'), ('rejected', 'Rejected'), ('unknown', 'Check / Unknown'), ('draft', 'Draft Prepared'), ('applied', 'Applied'), ('closed', 'Closed')], default='new')),
                ('fit_score', models.PositiveSmallIntegerField(default=0)),
                ('freshness_label', models.CharField(max_length=120, blank=True)),
                ('freshness_confidence', models.PositiveSmallIntegerField(default=0)),
                ('estimated_first_seen', models.DateTimeField(null=True, blank=True)),
                ('declared_posted_at', models.DateTimeField(null=True, blank=True)),
                ('first_seen_by_portal', models.DateTimeField(default=timezone.now)),
                ('last_seen', models.DateTimeField(default=timezone.now)),
                ('data_downloaded_bytes', models.PositiveBigIntegerField(default=0)),
                ('recommendation_reason', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('duplicate_of', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, related_name='rediscoveries', to='portal.opportunity')),
                ('suppressed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='OpportunityEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='portal.opportunity')),
                ('kind', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=200)),
                ('value', models.TextField()),
                ('source_url', models.URLField(max_length=1000, blank=True)),
                ('confidence', models.PositiveSmallIntegerField(default=50)),
                ('observed_at', models.DateTimeField(default=timezone.now)),
                ('metadata', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ['-observed_at']},
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='portal.opportunity')),
                ('status', models.CharField(max_length=30, choices=[('prepared', 'Prepared'), ('draft', 'Saved to Drafts'), ('suppressed', 'Draft suppressed'), ('applied', 'Applied'), ('reply', 'Reply received'), ('interview', 'Interview / progressing'), ('rejected', 'Rejected'), ('accepted', 'Accepted / engaged'), ('closed', 'Closed')], default='prepared')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, related_name='applications_as_cv', to='portal.documentasset')),
                ('cover_letter', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, related_name='applications_as_cover', to='portal.documentasset')),
                ('generated_cv', models.FileField(upload_to='generated/%Y/%m/', blank=True)),
                ('generated_cv_pdf', models.FileField(upload_to='generated/%Y/%m/', blank=True)),
                ('email_subject', models.CharField(max_length=500, blank=True)),
                ('email_body', models.TextField(blank=True)),
                ('email_mode', models.CharField(max_length=10, choices=[('plain', 'Plain text'), ('html', 'HTML')], default='plain')),
                ('website_answers', models.JSONField(default=dict, blank=True)),
                ('imap_draft_folder', models.CharField(max_length=200, blank=True)),
                ('imap_draft_uid', models.CharField(max_length=100, blank=True)),
                ('imap_message_id', models.CharField(max_length=300, blank=True)),
                ('draft_suppressed_until', models.DateTimeField(null=True, blank=True)),
                ('draft_suppression_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Application/import notes and outcome context.')),
                ('applied_at', models.DateTimeField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedTextVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_versions', to='portal.application')),
                ('kind', models.CharField(max_length=40, default='email')),
                ('provider', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=500, blank=True)),
                ('body', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='EmailProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=20, choices=[('internal', 'Internal Development'), ('external', 'External Mail')], unique=True)),
                ('active', models.BooleanField(default=False)),
                ('imap_host', models.CharField(max_length=255, blank=True)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_ssl', models.BooleanField(default=True)),
                ('imap_email', models.EmailField(blank=True)),
                ('imap_username', models.CharField(max_length=255, blank=True)),
                ('imap_password_enc', models.TextField(blank=True)),
                ('inbox_folder', models.CharField(max_length=200, default='INBOX')),
                ('sent_folder', models.CharField(max_length=200, default='Sent')),
                ('drafts_folder', models.CharField(max_length=200, default='Drafts')),
                ('smtp_host', models.CharField(max_length=255, blank=True)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_tls', models.BooleanField(default=True)),
                ('smtp_username', models.CharField(max_length=255, blank=True)),
                ('smtp_password_enc', models.TextField(blank=True)),
                ('notification_from_name', models.CharField(max_length=200, default='Application Portal')),
                ('notification_from_email', models.EmailField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30, choices=[('notification', 'Portal notification'), ('sent', 'Observed application sent'), ('inbox', 'Observed inbound'), ('draft', 'Draft saved'), ('draft_delete', 'Draft deleted')])),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, related_name='mail_events', to='portal.application')),
                ('subject', models.CharField(max_length=500, blank=True)),
                ('sender', models.CharField(max_length=500, blank=True)),
                ('recipients', models.TextField(blank=True)),
                ('message_id', models.CharField(max_length=500, blank=True)),
                ('folder', models.CharField(max_length=200, blank=True)),
                ('uid', models.CharField(max_length=100, blank=True)),
                ('body_excerpt', models.TextField(blank=True)),
                ('raw_original_sender', models.CharField(max_length=500, blank=True)),
                ('classification', models.CharField(max_length=80, blank=True)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('occurred_at', models.DateTimeField(default=timezone.now)),
                ('metadata', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ['-occurred_at']},
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(unique=True)),
                ('name', models.CharField(max_length=200, blank=True)),
                ('company', models.CharField(max_length=200, blank=True)),
                ('title', models.CharField(max_length=200, blank=True)),
                ('source', models.CharField(max_length=120, blank=True)),
                ('generic', models.BooleanField(default=False)),
                ('confidence', models.PositiveSmallIntegerField(default=50)),
                ('notes', models.TextField(blank=True)),
                ('last_seen', models.DateTimeField(default=timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20, choices=[('text', 'Free text'), ('document', 'Uploaded document'), ('mail', 'Mailbox scan')])),
                ('company', models.CharField(max_length=220, blank=True)),
                ('role_title', models.CharField(max_length=300, blank=True)),
                ('url', models.URLField(max_length=1000, blank=True)),
                ('email', models.EmailField(blank=True)),
                ('date_applied', models.DateTimeField(null=True, blank=True)),
                ('channel', models.CharField(max_length=30, blank=True, default='')),
                ('outcome_status', models.CharField(max_length=30, blank=True, default='', help_text='Imported application status/outcome; blank when the source does not say.')),
                ('notes', models.TextField(blank=True, default='', help_text='Dedicated imported notes; preserved into applied-role history.')),
                ('confidence', models.PositiveSmallIntegerField(default=50)),
                ('raw_excerpt', models.TextField(blank=True)),
                ('inference_method', models.CharField(max_length=40, default='heuristic', help_text='ai or heuristic fallback')),
                ('inference_metadata', models.JSONField(default=dict, blank=True)),
                ('imported', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='TrackingLinkRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('base_path', models.CharField(max_length=500, help_text='Example: /blog/winqemu')),
                ('destination_url', models.URLField(max_length=1000)),
                ('article_title', models.CharField(max_length=300, blank=True)),
                ('article_keywords', models.TextField(blank=True, help_text='Comma-separated article-native suffix words such as build, exe, vs')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='portal.trackinglinkrule')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, related_name='tracking_links', to='portal.application')),
                ('suffix', models.CharField(max_length=120)),
                ('path', models.CharField(max_length=700, unique=True)),
                ('full_url', models.URLField(max_length=1000, unique=True)),
                ('retired', models.BooleanField(default=False)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('likely_human_clicks', models.PositiveIntegerField(default=0)),
                ('first_click', models.DateTimeField(null=True, blank=True)),
                ('last_click', models.DateTimeField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='portal.trackinglink')),
                ('source_key', models.CharField(max_length=160, unique=True)),
                ('viewed_at', models.DateTimeField(default=timezone.now)),
                ('ip_address', models.CharField(max_length=255, blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.TextField(blank=True)),
                ('likely_bot', models.BooleanField(default=False)),
                ('source_table', models.CharField(max_length=80, default='request_logs')),
                ('raw_uri', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['-viewed_at']},
        ),
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30, choices=[('ollama', 'Ollama local'), ('openai', 'OpenAI'), ('gemini', 'Gemini')], unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('base_url', models.CharField(max_length=500, blank=True)),
                ('api_key_enc', models.TextField(blank=True)),
                ('default_model', models.CharField(max_length=200, blank=True)),
                ('stage_routes', models.JSONField(default=dict, blank=True)),
                ('last_test_ok', models.BooleanField(default=False)),
                ('last_test_message', models.TextField(blank=True)),
                ('last_test_at', models.DateTimeField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsageMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(default=timezone.now)),
                ('category', models.CharField(max_length=80)),
                ('provider', models.CharField(max_length=120, blank=True)),
                ('model', models.CharField(max_length=200, blank=True)),
                ('stage', models.CharField(max_length=120, blank=True)),
                ('requests', models.PositiveIntegerField(default=0)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('pages', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('bytes_downloaded', models.PositiveBigIntegerField(default=0)),
                ('metadata', models.JSONField(default=dict, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogStatsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('host', models.CharField(max_length=255, blank=True)),
                ('port', models.PositiveIntegerField(default=3306)),
                ('database', models.CharField(max_length=120, blank=True)),
                ('username', models.CharField(max_length=120, blank=True)),
                ('password_enc', models.TextField(blank=True)),
                ('query_mode', models.CharField(max_length=30, default='toughdev_native')),
                ('view_name', models.CharField(max_length=120, default='portal_shortlink_pageviews')),
                ('table_name', models.CharField(max_length=120, default='pageviews')),
                ('method_column', models.CharField(max_length=120, blank=True)),
                ('path_column', models.CharField(max_length=120, default='page_id')),
                ('timestamp_column', models.CharField(max_length=120, default='last_accessed')),
                ('user_agent_column', models.CharField(max_length=120, default='last_useragent')),
                ('ip_column', models.CharField(max_length=120, default='user_ip')),
                ('method_value', models.CharField(max_length=80, blank=True)),
                ('last_sync', models.DateTimeField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=220)),
                ('country', models.CharField(max_length=120, blank=True)),
                ('match_summary', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True)),
                ('source_url', models.URLField(max_length=1000, blank=True)),
                ('contact_name', models.CharField(max_length=200, blank=True)),
                ('contact_email', models.EmailField(blank=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(max_length=40, default='review')),
                ('draft_subject', models.CharField(max_length=500, blank=True)),
                ('draft_body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(default=timezone.now)),
                ('actor', models.CharField(max_length=200, blank=True)),
                ('action', models.CharField(max_length=120)),
                ('object_type', models.CharField(max_length=120, blank=True)),
                ('object_id', models.CharField(max_length=120, blank=True)),
                ('summary', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict, blank=True)),
            ],
            options={'ordering': ['-at']},
        ),
        migrations.CreateModel(
            name='PerformanceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40, choices=[('chat', 'Simple chat'), ('search', 'Search provider test'), ('scrape', 'Page scrape'), ('summarize', 'Summarize content'), ('extract', 'JD extraction'), ('rank', 'Opportunity ranking'), ('docx_to_pdf', 'DOCX to PDF conversion')])),
                ('provider', models.CharField(max_length=80, blank=True)),
                ('model', models.CharField(max_length=200, blank=True)),
                ('device', models.CharField(max_length=80, blank=True, help_text='Informational device/runtime selection for the lab.')),
                ('input_text', models.TextField(blank=True)),
                ('input_url', models.URLField(max_length=1000, blank=True)),
                ('output_text', models.TextField(blank=True)),
                ('ok', models.BooleanField(default=False)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('bytes_downloaded', models.PositiveBigIntegerField(default=0)),
                ('metadata', models.JSONField(default=dict, blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=timezone.now)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_saved_filters', to=settings.AUTH_USER_MODEL)),
                ('screen', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('query_string', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'unique_together': {('owner', 'screen', 'name')}, 'ordering': ['screen', 'name']},
        ),
    ]
