# Generated by ScoutBox v0.10.84
from django.db import migrations, models


def clamp_existing_values(apps, schema_editor):
    PortalSettings = apps.get_model('portal', 'PortalSettings')
    for row in PortalSettings.objects.all():
        try:
            value = int(getattr(row, 'max_concurrent_campaigns', 5) or 5)
        except Exception:
            value = 5
        value = max(2, min(10, value))
        if getattr(row, 'max_concurrent_campaigns', None) != value:
            row.max_concurrent_campaigns = value
            row.save(update_fields=['max_concurrent_campaigns'])


class Migration(migrations.Migration):
    dependencies = [
        ('portal', '0109_v01081_campaign_run_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalsettings',
            name='max_concurrent_campaigns',
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text='Maximum automatic primary campaign runs ScoutBox may have queued or running at once. Clamp range: 2-10.',
            ),
        ),
        migrations.AlterField(
            model_name='sourceblacklist',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterModelOptions(
            name='sourceblacklist',
            options={'ordering': ['domain', 'label']},
        ),
        migrations.RunPython(clamp_existing_values, migrations.RunPython.noop),
    ]
