from django.urls import path
from . import views

urlpatterns=[
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('',views.dashboard,name='dashboard'),
    path('quick-start/',views.quick_start,name='quick_start'),
    path('about/',views.about_view,name='about'), path('about/export-docx/',views.about_export_docx,name='about_export_docx'),
    path('activity/status/',views.activity_status,name='activity_status'),
    path('filters/state/',views.save_list_filter_state,name='save_list_filter_state'),
    path('dashboard/activity-data/',views.dashboard_activity_data,name='dashboard_activity_data'),
    path('dashboard/live/',views.dashboard_live_data,name='dashboard_live_data'),
    path('dashboard/errors/ack/',views.dashboard_error_ack,name='dashboard_error_ack'),
    path('jobs/<int:pk>/status/',views.background_job_status,name='background_job_status'),
    path('jobs/<int:pk>/cancel/',views.background_job_cancel,name='background_job_cancel'),
    path('jobs/<int:pk>/skip-current/',views.background_job_skip_current,name='background_job_skip_current'),
    path('jobs/<int:pk>/raw-preview/',views.search_provider_raw_preview,name='search_provider_raw_preview'),
    path('read-state/<str:kind>/<int:pk>/',views.item_read_state,name='item_read_state'),
    path('attention/counts/',views.attention_counts,name='attention_counts'),
    path('re-evaluation/scope-counts/<str:kind>/',views.re_evaluation_scope_counts,name='re_evaluation_scope_counts'),
    path('re-evaluation/results/<str:kind>/<int:pk>/export/',views.re_evaluation_results_export,name='re_evaluation_results_export'),
    path('search-sources/<int:pk>/test/',views.search_provider_test_async,name='search_provider_test_async'),
    path('chatbot/ask/',views.chatbot_ask,name='chatbot_ask'), path('chatbot/history/',views.chatbot_history,name='chatbot_history'), path('chatbot/export/',views.chatbot_export,name='chatbot_export'), path('chatbot/test/',views.chatbot_test,name='chatbot_test'),
    path('background/toggle/',views.toggle_background,name='toggle_background'),
    path('profile/',views.profile_view,name='profile'), path('profile/defaults/',views.profile_defaults_async,name='profile_defaults_async'), path('profile/autopopulate/',views.profile_autopopulate_async,name='profile_autopopulate_async'), path('profile/campaign-templates/',views.profile_campaign_templates_async,name='profile_campaign_templates_async'), path('scope/',views.scope_view,name='scope'),
    path('sources/',views.sources_view,name='sources'),
    path('facebook-pages/',views.facebook_pages_view,name='facebook_pages'),
    path('campaigns/',views.campaigns_view,name='campaigns'), path('campaigns/<int:pk>/',views.campaign_detail,name='campaign_detail'), path('campaigns/<int:pk>/rotation/',views.campaign_rotation_data,name='campaign_rotation_data'),
    path('opportunities/',views.opportunities_view,name='opportunities'), path('opportunities/<int:pk>/',views.opportunity_detail,name='opportunity_detail'),
    path('companies/',views.company_intel_view,name='companies'), path('imports/',views.import_view,name='imports'), path('applied/',views.applied_view,name='applied'), path('applied/<int:pk>/edit/',views.applied_edit,name='applied_edit'),
    path('applications/',views.applications_view,name='applications'), path('applications/<int:pk>/edit/',views.application_edit,name='application_edit'), path('applications/<int:pk>/save-async/',views.application_save_async,name='application_save_async'), path('applications/<int:pk>/tool-async/',views.application_tool_async,name='application_tool_async'), path('applications/<int:pk>/state/',views.application_state_api,name='application_state_api'),
    path('applications/<int:pk>/save-draft/',views.application_save_draft,name='application_save_draft'), path('applications/<int:pk>/delete-draft/',views.application_delete_draft,name='application_delete_draft'),
    path('applications/<int:pk>/force-draft/',views.application_force_draft,name='application_force_draft'),
    path('email-config/',views.email_config_view,name='email_config'), path('email-config/test/',views.email_profile_test_async,name='email_profile_test_async'), path('email-config/browser/',views.email_browser_api,name='email_browser_api'), path('email-history/',views.email_history_view,name='email_history'), path('email-history/<int:pk>/body/',views.email_event_body,name='email_event_body'), path('contacts/',views.contacts_view,name='contacts'),
    path('links/rules/',views.link_rules_view,name='link_rules'), path('links/rules/test-async/',views.tracking_link_test_async,name='tracking_link_test_async'), path('links/',views.links_view,name='links'),
    path('ai/',views.ai_view,name='ai'), path('ai/test/',views.ai_test_async,name='ai_test_async'), path('ai/providers/validate/',views.ai_provider_validate,name='ai_provider_validate'), path('ai/providers/test/',views.ai_provider_test_live,name='ai_provider_test_live'), path('ai/providers/save/',views.ai_provider_save,name='ai_provider_save'), path('performance/',views.performance_view,name='performance'), path('telemetry/',views.telemetry_view,name='telemetry'), path('telemetry/live/',views.telemetry_live,name='telemetry_live'), path('stats/',views.stats_view,name='stats'), path('stats/live/',views.stats_live,name='stats_live'), path('stats/map/resolve/',views.stats_map_resolve_async,name='stats_map_resolve'),
    path('cold-contact/',views.cold_contact_view,name='cold_contact'), path('cold-contact/<int:pk>/',views.hidden_lead_detail,name='hidden_lead_detail'), path('blacklist/',views.blacklist_view,name='blacklist'), path('search-log/',views.search_log_view,name='search_log'), path('gpt-log/',views.gpt_log_view,name='gpt_log'), path('gpt-log/<int:pk>/',views.gpt_log_detail,name='gpt_log_detail'), path('audit/',views.audit_view,name='audit'), path('settings/',views.settings_view,name='settings'), path('settings/maintenance-capabilities/',views.maintenance_capabilities,name='maintenance_capabilities'), path('settings/export-diagnostics/',views.export_diagnostic_data,name='export_diagnostic_data'), path('settings/export-diagnostics/estimate/',views.diagnostic_export_estimate,name='diagnostic_export_estimate'), path('settings/export-diagnostics/<int:pk>/download/',views.diagnostic_export_download,name='diagnostic_export_download'), path('recycle-bin/',views.recycle_bin_view,name='recycle_bin'), path('settings/blog-test/',views.blog_stats_test_async,name='blog_stats_test_async'), path('health/',views.health_view,name='health'),
]
